version: '0.2'
phases:
  install:
    runtime-versions:
      nodejs: 18.20.4
    commands:
      - echo Installing dependencies...
      - npm install --force
  pre_build:
    commands:
      - echo Building project...
      - npm run build --verbose
  build:
    commands:
      - echo ID_OShN87LI
      - echo Creating tar.gz archive of build files...
      - cd dist
      - tar -czvf ../PLN6000122.tar.gz *
  post_build:
    commands:
      - echo Pushing artifacts...
artifacts:
  files:
    - PLN6000122.tar.gz
